spring:
  datasource:
    url:
      jdbc:mysql://125.220.157.225:13309/lib_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username:
      root
    password:
      123456
  jpa:
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto:
      update
    show-sql:
      true

server:
  port: 27023
